#!/bin/sh

# Copyright (C) 2009, Progress Software Corporation and/or its
# subsidiaries or affiliates.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
# 
#     http://www.apache.org/licenses/LICENSE-2.0
# 
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

APP_HOME=`dirname $0`

APPCP=$APP_HOME/../conf
for jar in $APP_HOME/../lib/*.jar 
do
  APPCP=$APPCP:${jar}
done

export PATH=$PATH:$APP_HOME/../lib

java -classpath $APPCP com.fusesource.forge.jmstest.frontend.Benchmark $@

